# Generated by Django 2.2.3 on 2021-04-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210428_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=0, help_text='Максимум 25 символів', max_length=25, verbose_name='Назва публікації'),
        ),
    ]
