# Generated by Django 2.2.3 on 2021-04-28 13:22

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210428_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=blog.models.default_datetime),
        ),
    ]
