# Generated by Django 2.2.3 on 2021-04-28 13:28

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default=0, help_text='Максимум 250 символів', max_length=250, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=blog.models.default_datetime, verbose_name='Дата'),
        ),
    ]
