# Generated by Django 2.2.3 on 2021-04-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210428_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='bbbb', verbose_name='Слаг'),
        ),
    ]
