# Generated by Django 2.2.3 on 2021-04-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210428_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Назва публікації', 'verbose_name_plural': 'Назва для публікацій'},
        ),
    ]
