# Generated by Django 2.2.3 on 2021-04-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210428_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(default='детектив', help_text='Максимум 250 символів', max_length=250, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='назва', help_text='Максимум 25 символів', max_length=25, verbose_name='Назва публікації'),
        ),
    ]
