# Generated by Django 2.2.3 on 2021-04-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210429_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='slug_in',
            new_name='slug',
        ),
    ]
