# Generated by Django 2.2.3 on 2021-04-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210429_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(default='детектив', help_text='Максимум 1250 символів', max_length=1250, verbose_name='Опис'),
        ),
    ]
